
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLOR HOW KIND MANY MATERIAL NUMBER OPERATE SIZEcommand : OPERATE NUMBER articlecommand : HOW MANY articleattribute : COLORattribute : MATERIALattribute : SIZEattribute : KINDarticle : attribute attribute attribute attribute'
    
_lr_action_items = {'OPERATE':([0,],[2,]),'HOW':([0,],[3,]),'$end':([1,6,8,9,10,11,12,15,],[0,-1,-3,-4,-5,-6,-2,-7,]),'NUMBER':([2,],[4,]),'MANY':([3,],[5,]),'COLOR':([4,5,7,8,9,10,11,13,14,],[8,8,8,-3,-4,-5,-6,8,8,]),'MATERIAL':([4,5,7,8,9,10,11,13,14,],[9,9,9,-3,-4,-5,-6,9,9,]),'SIZE':([4,5,7,8,9,10,11,13,14,],[10,10,10,-3,-4,-5,-6,10,10,]),'KIND':([4,5,7,8,9,10,11,13,14,],[11,11,11,-3,-4,-5,-6,11,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'article':([4,5,],[6,12,]),'attribute':([4,5,7,13,14,],[7,7,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> OPERATE NUMBER article','command',3,'p_command','ply.py',20),
  ('command -> HOW MANY article','command',3,'p_command_howmany','ply.py',38),
  ('attribute -> COLOR','attribute',1,'p_attribute_color','ply.py',121),
  ('attribute -> MATERIAL','attribute',1,'p_attribute_material','ply.py',126),
  ('attribute -> SIZE','attribute',1,'p_attribute_size','ply.py',131),
  ('attribute -> KIND','attribute',1,'p_attribute_kind','ply.py',136),
  ('article -> attribute attribute attribute attribute','article',4,'p_article_attribute','ply.py',141),
]
